### ISSUE TITLE
Typo in /usr/share/dict/web2

### ISSUE THREAD

**Issue by mandeluna** [386bsd/386bsd#3]
The word "potate" appears in the dictionary. As far as I can tell it is not in any of the Webster's Dictionaries generally cited as a source for this dictionary.

It seems this typo has been in there at least since 1994. It is also in FreeBSD, NetBSD, OpenBSD and OS X dictionaries, but it does not appear in any Linux dictionary I could find nor in the 4.2 or 4.3 BSD sources.

To be honest this is not critical but I'm kind of curious as to how it originated. I'm assuming it's a transcription error when the dictionary was typed in but this seems to be the place it first turned up.

**Comment by lynnejolitz** [comment]
The only place I could find a definition for this word was in "A Dictionary of Slang, Jargon & Cant: Embracing English, American, and Anglo-Indian Slang, Pidgin English, Tinker's Jargon and Other Irregular Phraseology", Volume 1, edited by Albert Barrère, Charles Godfrey Leland (Ballantyne Press, 1890) on page 148. "Potate (American), signifying to drink; an abbreviation from potation, as the kindred but more permissible vulgarism orate, from oration. The last word has already been naturalized in English, but potate remains an alien." /usr/dict/words has been around since Version 6 Unix (Berkeley Unix is /usr/dict/share/words). Dennis Ritchie was the one who put it into Unix when Webster's Dictionary copyright 1934 became public domain when the copyright expired. I would have to go back and research our online sources to see if it was in early versions but later removed. It's clear it is a word. Knowing Dennis and his sense of humor, and the hard-drinking nature of the early Unix days, he would have liked this word. Lynne.

**Comment by mandeluna** [comment]
That's beautiful. Thanks!
